FROM maven:3.8.1-openjdk-16

ENV H2_DB ${H2_DB}
ENV H2_USERNAME ${H2_USERNAME}
ENV H2_PASSWORD ${H2_PASSWORD}
ENV GITHUB_PERSONAL_ACCESS_TOKEN ${GITHUB_PERSONAL_ACCESS_TOKEN}
ENV GITHUB_APP_OWNER_USERNAME ${GITHUB_APP_OWNER_USERNAME}

COPY ./ ./

RUN mvn clean package

CMD ["java", "-jar", "target/githubstats-0.0.1-SNAPSHOT.jar"]